### ISSUE TITLE
Feature: Days of Supply

### ISSUE THREAD

**Issue by ReneSchroederLJ** [eclipse-tractusx/puris#313]
**As** a user of the PURIS FOSS application,

**I want** to to access my own and customer's Days of Supply in the Dashboard view,

**so that** I can get an overview of the supply situation.

### Tasks
- [ ] https://github.com/eclipse-tractusx/puris/issues/309
- [ ] https://github.com/eclipse-tractusx/puris/issues/311
- [ ] https://github.com/eclipse-tractusx/puris/issues/312
