### ISSUE TITLE
Feature: Messaging view

### ISSUE THREAD

**Issue by ReneSchroederLJ** [eclipse-tractusx/puris#317]
**As** ... ,
**I want** ... ,
**so that** ... .

## Hints / Details

- ...

### Outcome
- ...
### Acceptance Criteria
- ...

## Out of Scope

- ...

### Tasks
- [ ] https://github.com/eclipse-tractusx/puris/issues/316
- [ ] https://github.com/eclipse-tractusx/puris/issues/196
- [ ] https://github.com/eclipse-tractusx/puris/issues/193
- [ ] https://github.com/eclipse-tractusx/puris/issues/194
- [ ] https://github.com/eclipse-tractusx/puris/issues/315
