### ISSUE TITLE
[R24.08] Quality Gate Checklist

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/puris#498]
## QG checks

Please open and fill in this issue in your product repository to document the compliance with our Tractus-X Release Guideline (TRGs)

**Show compliance with TRGs** by referencing to a tagged link in the respective repository where possible, example: TRG 1.01 (see [github.com/eclipse-tractusx/example-repo/tree/1.0.0/README.md](https://github.com/eclipse-tractusx/example-repo/tree/1.0.0/README.md))

### Close this issue once the compliance with the TRGs has been documented

Committer(s): @tom-rm-meyer-ISST 
Helm Chart Version: 2.7.0
App Version: 2.1.0

Release Management Reference Issue: https://github.com/eclipse-tractusx/sig-release/issues/795

### Check of Tractus-X Release Guidelines

- Currently implemented automatic checks can be found under your product on our [Release Guidelines Checks Board](https://eclipse-tractusx.github.io/sig-release/)
- This QG Check is depending on the mandatory information from our current [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)

#### TRG 1 Documentation

- [x] [TRG 1.01](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1) appropriate `README.md` (see [here](https://github.com/eclipse-tractusx/puris/blob/2.1.0/README.md))
- [x] [TRG 1.02](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2) appropriate install instructions either `INSTALL.md` or in `README.md` (see [INSTALL.md](https://github.com/eclipse-tractusx/puris/blob/2.1.0/INSTALL.md) and [Chart README.md](https://github.com/eclipse-tractusx/puris/blob/2.1.0/charts/puris/README.md#install))
- [x] [TRG 1.03](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3) appropriate `CHANGELOG.md` (see [here](https://github.com/eclipse-tractusx/puris/blob/2.1.0/CHANGELOG.md#v210))
- [x] [TRG 1.04](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4) editable static files (see [here](https://github.com/eclipse-tractusx/puris/tree/2.1.0/docs/architecture/puml))
- [x] [TRG 1.05](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-05) architecture documentation (see [here](https://github.com/eclipse-tractusx/puris/tree/2.1.0/docs/architecture))
- [x] [TRG 1.06](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-06) administrator's guide (see [here](https://github.com/eclipse-tractusx/puris/tree/2.1.0/docs/admin))
- [x] [TRG 1.07](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-07) user guide available (see [README.md](https://github.com/eclipse-tractusx/puris/blob/2.1.0/docs/README.md) and [userGuide](https://github.com/eclipse-tractusx/puris/blob/2.1.0/docs/user/User_Guide.md))
- [x] [TRG 1.08](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-08) open api documentation available (see [README.md](https://github.com/eclipse-tractusx/puris/blob/2.1.0/docs/api/openAPI.yaml))

#### TRG 2 Git

- [x] [TRG 2.01](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1) default branch is named `main` (see [here](https://github.com/eclipse-tractusx/puris/branches))
- [x] [TRG 2.03](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3) repository structure (see [quality gate action run](https://github.com/eclipse-tractusx/puris/pull/518))
- [x] [TRG 2.04](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4) leading product repository (see [here](https://github.com/eclipse-tractusx/puris/blob/2.1.0/README.md) but only this repo)
- [x] [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5) `.tractusx` metafile in a proper format (see [here](https://github.com/eclipse-tractusx/puris/blob/2.1.0/.tractusx))
- [x] [TRG 2.06](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-6) Dependabot (see [here](https://github.com/eclipse-tractusx/puris/blob/2.1.0/.github/dependabot.yml))

#### TRG 3 Kubernetes

- [x] [TRG 3.02](https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2) persistent volume and persistent volume claim or database dependency (subchart) are in place when needed (see [chart of dependency postgresql](https://github.com/eclipse-tractusx/puris/blob/2.1.0/charts/puris/Chart.yaml#L30))

#### TRG 4 Container

- [x] [TRG 4.01](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-01) [semantic versioning](https://semver.org/) and tagging  (see [frontend](https://hub.docker.com/layers/tractusx/app-puris-frontend/2.1/images/sha256-b9178f1d6a6958113a8a176cd599e5323793f2c2f0e5c045efad177daadbf0bf?context=explore), [backend](https://hub.docker.com/layers/tractusx/app-puris-backend/2.1/images/sha256-e77dc6dba211b097e3bd27254d36a6e58f4a1ed58e83a493b58b5b26c79cab26?context=explore))
- [x] [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02) base image is agreed   (see [frontend](https://github.com/eclipse-tractusx/puris/blob/2.1.0/frontend/Dockerfile.prebuilt#L23), [backend](https://github.com/eclipse-tractusx/puris/blob/2.1.0/backend/Dockerfile#L33))
- [x] [TRG 4.03](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03) image has `USER` command and Non Root Container (see [frontend](https://github.com/eclipse-tractusx/puris/blob/2.1.0/frontend/Dockerfile.prebuilt#L43), [backend](https://github.com/eclipse-tractusx/puris/blob/2.1.0/backend/Dockerfile#L40))
- [x] [TRG 4.05](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05) released image must be placed in `DockerHub`, remove `GHCR` references  (see [frontend](https://hub.docker.com/layers/tractusx/app-puris-frontend/2.1/images/sha256-3637955a422f089f065f68e819c7738e2742f7ea00e53fa7761dd3e9225b22f5?context=explore), [backend](https://hub.docker.com/layers/tractusx/app-puris-backend/2.1/images/sha256-30e332ef57493366c4436435e26c554b4c51268cfe92fbec6cdd20641ec4de75?context=explore))
- [x] [TRG 4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06) separate notice file for `DockerHub` has all necessary information (see [frontend](https://github.com/eclipse-tractusx/puris/blob/2.1.0/frontend/DOCKER_NOTICE.md), [backend](https://github.com/eclipse-tractusx/puris/blob/2.1.0/backend/DOCKER_NOTICE.md))
- [x] [TRG 4.07](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-07) root file system is set to read access by default, but can be overwritten by the user (see [frontend](https://github.com/eclipse-tractusx/puris/blob/2.1.0/charts/puris/values.yaml#L60), [backend](https://github.com/eclipse-tractusx/puris/blob/2.1.0/charts/puris/values.yaml#L256))
- [x] [TRG 4.08](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-08) multi platform builds (see [frontend](https://github.com/eclipse-tractusx/puris/blob/2.1.0/.github/workflows/build-image-frontend.yml#L97), [backend](https://github.com/eclipse-tractusx/puris/blob/2.1.0/.github/workflows/build-image-backend.yml#L65))

#### TRG 5 Helm

- [x] [TRG 5.01](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01) Helm chart requirements (see [here](https://github.com/eclipse-tractusx/puris/tree/2.1.0/charts/puris))
- [x] [TRG 5.02](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02) Helm chart location in `/charts` directory and correct structure (see [quality gate action run](https://github.com/eclipse-tractusx/puris/pull/518))
- [x] [TRG 5.03](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-03) proper version strategy  (see [here](https://github.com/eclipse-tractusx/puris/blob/2.1.0/charts/puris/Chart.yaml))
- [x] [TRG 5.04](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04) CPU / MEM resource requests and limits and are properly set (see [frontend](https://github.com/eclipse-tractusx/puris/blob/2.1.0/charts/puris/values.yaml#L95), [backend](https://github.com/eclipse-tractusx/puris/blob/2.1.0/charts/puris/values.yaml#L272))
- [x] [TRG 5.06](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06) Application must be configurable through the Helm chart  (see [here](https://github.com/eclipse-tractusx/puris/blob/2.1.0/charts/puris/values.yaml))
- [x] [TRG 5.07](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07) Dependencies are present and properly configured in the Chart.yaml (see dependency, [config](https://github.com/eclipse-tractusx/puris/blob/2.1.0/charts/puris/values.yaml#L496))
- [x] [TRG 5.08](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08) Product has a single deployable helm chart that contains all components  (see [here](https://github.com/eclipse-tractusx/puris/blob/2.1.0/charts/puris/Chart.yaml))
- [x] [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) Helm Test running properly (see [here](https://github.com/eclipse-tractusx/puris/actions/runs/10108150994/job/27953437680))
- [x] [TRG 5.10](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10) Products need to support 3 versions at a time (see [v1.28.9](https://github.com/eclipse-tractusx/puris/actions/runs/10108630748/job/27954947302), [v1.29.4](https://github.com/eclipse-tractusx/puris/actions/runs/10108664548), [v1.30.0](https://github.com/eclipse-tractusx/puris/actions/runs/10108683139))
- [x] [TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11) Upgradeability (see [here](https://github.com/eclipse-tractusx/puris/actions/runs/10108150994/job/27953437680))
 
#### TRG 6 Released Helm Chart

- [x] [TRG 6.01](https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1) Released Helm Chart  (see [here](https://github.com/eclipse-tractusx/puris/releases/tag/puris-2.7.0))

#### TRG 7 Open Source Governance
- [x] [TRG 7.01](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01) Legal Documentation (see [here](https://github.com/eclipse-tractusx/puris/tree/2.1.0))
- [x] [TRG 7.02](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) License and copyright header  (see [updated](https://github.com/eclipse-tractusx/puris/pull/527))
- [x] [TRG 7.03](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03) IP checks for project content  (see [here](https://github.com/eclipse-tractusx/puris/pulls?q=is%3Apr+is%3Aclosed))
- [x] [TRG 7.04](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04) IP checks for 3rd party content (see [DEPENDENCIES_BACKEND](https://github.com/eclipse-tractusx/puris/blob/2.1.0/DEPENDENCIES_BACKEND), [DEPENDENCIES_FRONTEND](https://github.com/eclipse-tractusx/puris/blob/2.1.0/DEPENDENCIES_FRONTEND))
- [x] [TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05) Legal information for distributions (see [frontend](https://github.com/eclipse-tractusx/puris/blob/2.1.0/.github/workflows/build-image-frontend.yml#L88), [backend](https://github.com/eclipse-tractusx/puris/blob/2.1.0/.github/workflows/build-image-backend.yml#L56))
- [x] [TRG 7.06](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06) Legal information for end user content (see [here](https://github.com/eclipse-tractusx/puris/blob/2.1.0/.github/workflows/build-image-frontend.yml#L72))
- [x] [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07) Legal notice for documentation (see [here](https://github.com/eclipse-tractusx/puris/tree/2.1.0/docs/user/img), [here](https://github.com/eclipse-tractusx/puris/tree/2.1.0/docs/architecture/img), [all docs](https://github.com/eclipse-tractusx/puris/blob/2.1.0/docs/README.md))
- [x] [TRG 7.08](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08) Legal notice for KIT documentation (see as above / not a kit but non_code parts)

#### TRG 8 Security
- [x] [TRG 8.01](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-01) Mitigate high and above findings in CodeQL (see [here](https://github.com/eclipse-tractusx/puris/security/code-scanning))
- [x] [TRG 8.02](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-02) Mitigate high and above findings in KICS (see [here](https://github.com/eclipse-tractusx/puris/security/code-scanning))
- [x] [TRG 8.04](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-04) Mitigate high and above findings in Trivy (see [here](https://github.com/eclipse-tractusx/puris/security/code-scanning))
- [x] [TRG 8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03) No secret findings by GitGuardian or TruffleHog (see [here](https://github.com/eclipse-tractusx/puris/security/code-scanning))

#### TRG UX/UI Styleguide
- [x] [TRG 9.01](https://eclipse-tractusx.github.io/docs/release/trg-9/trg-9-01) UX consistency / Styleguide for UI (see [Changelog](https://github.com/eclipse-tractusx/puris/blob/2.1.0/CHANGELOG.md) with Known Knowns)

#### Information Sharing

**Comment by tom-rm-meyer-ISST** [comment]
Done
